### ISSUE TITLE
Unable change state to Comfort through scenes in HA

### ISSUE THREAD

**Issue by mathijsblokland** [krocat/ToonHA#12]
If i want to change the `operation_mode` to **Comfort** i'm getting the following error:

```
WARNING (MainThread) [homeassistant.helpers.state] reproduce_state: Unable to reproduce state <state climate.toon_van_eneco=None; peration_mode=Comfort @ 2017-09-29T21:25:55.860364+02:00> (2)
```

I stumbled upon this error while i was configuring my amazon echo to communicate with Home Assistant and return the temperature or changing the operation mode. So i thought i was doing something wrong, but this also occurs when you click on the states buttons in the climate panel.

![](http://img.springe.st/20170929-27bvg.png)

Any clue on how to fix this, and if someone else can reproduce this? Thanks in advance.

**Comment by costastf** [comment]
I am not using scenes so not really sure what is going on. Can you update the thermostat state from the basic toon view in HA successfully? If so, then it could be the way you set up scenes. Please provide as much details as possible for your set up so I can try to help you.

**Comment by costastf** [comment]
@mathijsblokland Since you haven't come up with any feedback on this I will close it. If you do come up with feedback feel free to open it right back.

**Comment by mathijsblokland** [comment]
Hi @costastf, sorry for not replying but i haven't been able to work on my home automation for a while. Once i'm able to look into it again i'll post the details of my setup & configuration.
