### ISSUE TITLE
Exposing burner status as binary sensor 

### ISSUE THREAD

**Issue by boltgolt** [krocat/ToonHA#13]
I'd love to implement a binary_sensor for the burner status. The underlying toonlib already supports it through the `toon.thermostat_info.burner_info` property, as i'm sure you know. 

Just asking if that's a good addition, if it's something you don't find useful or out of scope i'll just bodge it together locally.

**Comment by costastf** [comment]
My take is that anything that you ended up needing is going to be something that someone else would probably need at some point too. So by all means please implement it and make an MR for the feature. Thanks!
