### ISSUE TITLE
mode unavailable

### ISSUE THREAD

**Issue by dreamfoxmedia** [krocat/ToonHA#31]
Hello,

with the default toon integration i was using google assistant to set temperature
With the custom toonHA when i give a command i always get:
that mode is not available.
how can i get it to work with google assistant (google home)

**Comment by costastf** [comment]
Hi @dreamfoxmedia , we are going to need a lot more info than that to be able to help you. How have you set up the interfacing, OS, some more concrete error message, actual version you are using...

**Comment by scheric** [comment]
@dreamfoxmedia you are not giving us a lot of information. 
I think I know the problem you have. I have experienced it myself. 

I have a custom thermostat using the `generic_thermostat` It is called `computerhok`

I haven’t seen any errors in the home assistant log. 
As you can see in the pictures I am getting the current temperature.  
If I ask google to do something with the `toon van eneco` thermostat she can’t do anything with it. 
If I ask google to do something with `computerhok` There are no problems. 

> sorry for the big pictures 

![6f09760a-8626-4ba1-b417-b76f296c81ec](https://user-images.githubusercontent.com/38077357/48290794-754b2b80-e474-11e8-83be-abf6702f24af.jpeg)
![a1425660-5be1-4023-a912-0f5b96debac5](https://user-images.githubusercontent.com/38077357/48290796-75e3c200-e474-11e8-95ad-9a94d2dc18e3.jpeg)

**Comment by scheric** [comment]
Home Assistant has fixed there integrated toon component in version 0.84 home-assistant/home-assistant#18966
