### ISSUE TITLE
warnings in install and logging  since HA version 0.81

### ISSUE THREAD

**Issue by MagieMalone** [krocat/ToonHA#42]
upgrade gives the following warning:
toonlib 1.0.2 has requirement cachetools==2.0.0, but you'll have cachetools 2.0.1 which is incompatible.
toonlib 1.0.2 has requirement requests==2.13.0, but you'll have requests 2.20.0 which is incompatible.
toonapilib 3.0.1 has requirement requests==2.18.4, but you'll have requests 2.20.0 which is incompatible.

HA log after starting:
2018-11-01 09:10:25 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.climate.toon. Make sure all dependencies are installed

running on hassbian.

**Comment by scheric** [comment]
That's quite strange. I am running home assistant on 0.81.2 and I am not having any errors. And my sensors are working. After a reboot.

**Comment by MagieMalone** [comment]
I'm on hassbian, maybe that's a contributing factor. Back when I started, there was no hass.io version for the new pi's

edit:
also despite the warnings it seems to work alright... wierd.

**Comment by scheric** [comment]
That could be a factor because I am using Hass.io. 

Or there is a conflict with the integrated toon component
home-assistant/home-assistant#18092

**Comment by costastf** [comment]
The unofficial api has been discontinued by eneco so toonlib will never work again. We need to update the official component to use the official api. Since this is kinda moot now, due to the above, closing it.
