### ISSUE TITLE
update 0.88 HA

### ISSUE THREAD

**Issue by PKonlinegithub** [krocat/ToonHA#46]
Hey,

After I installed the update 0.88 of HA, the plug-in of ToonHA (api) did not work anymore.
I received a warning in 0.87.1 but just ran the plugin. Now it is stopped. You may know a solution.
the say in there release:
We have tightened config validation, so expect a couple of new warnings. Platform configuration will no longer allow to contain keys that are not supported. This should help with finding typos in your current and future YAML configs. This will currently fallback to a warning and will become a full error in the future.

**Comment by costastf** [comment]
There is currently an effort with a new component in HA that will superseed this completely. This component will probably get no more development.
